### ISSUE TITLE
Exception serializing relaionship when using data type other than string for Ids

### ISSUE THREAD

**Issue by bmcockman** [codecutout/JsonApiSerializer#100]
When using int for Id instead of string, it works fine if not using relationships. However when serializing relationships a cast exception is thrown. I tracked the bug down to the ResourceIdentifierConverter as it writes Id's in a different manner to the ResourceObjectConverter and does not take into account different data types.

Good practice would suggest this code be in a shared place, and not duplicated to avoid these problems.

ResourceObjectConverter:
````
string id = null;
if (WriterUtil.ShouldWriteProperty(value, metadata.IdProperty, serializer, out object objId))
{
    //we will allow some non-string properties if it is trival to convert to a string
    if (!AllowedIdTypes.Contains(metadata.IdProperty.PropertyType))
        throw new JsonApiFormatException(
                writer.Path,
                $"Expected Id property to be a string or primitive but found it to be '{objId?.GetType()}'",
                "The values of the id member MUST be a string");

    id = objId as string ?? objId?.ToString();

    writer.WritePropertyName(PropertyNames.Id);
    writer.WriteValue(id);
}
````

ResourceIdentifierConverter:
````
WriterUtil.ShouldWriteProperty(resourceObject, resourceObjectContract.IdProperty, serializer, out string id);
writer.WritePropertyName(PropertyNames.Id);
writer.WriteValue(id);
````

**Comment by alex-davies** [comment]
This does look to be a bug, integer ids should work for relationships but they don't see to at the moment.

The two places this needs to be done in are writing resource-objects and writing resource-object-identifiers, these are two very different things and are handled differently which is why there is no 'shared place' for them. They do share quite a lot of utility methods but the id conversion still needs to be explicitly called. Although writing and ids and types might benefit from some specific utility methods
 
I have fixed this in 1.7.1 (https://github.com/codecutout/JsonApiSerializer/pull/101)
