### ISSUE TITLE
Multiple objects with same Id have the same reference

### ISSUE THREAD

**Issue by ikaman** [codecutout/JsonApiSerializer#30]
I would like to ask you if it is possible to create an option that objects with same Id don't have the same reference. 

For instance in my code I have a situation like this (approximately)

[DataContract]
public class Earth
{
[DataMember(Name = "id")]
public int Id {get;set;}

[DataMember(Name = "countries")]
public Country[] Countries {get;set;}
}

[DataContract]
public class Country
{
[DataMember(Name = "id")]
public int Id {get;set;}

[DataMember(Name = "people")]
public Person[] People {get;set;}
}

[DataContract]
public class Person
{
[DataMember(Name = "Name")]
public string Name {get;set;}

// this doesn't exist in the api
public Country Country {get;set;}
}

In this example I have list of countries in Earth. And in those countries i have a list of people. 

But people can live in multiple countries. As the deserializer cannot fill a country for each person (I would like a back link as well) I have to do something like this

foreach c in country
foreach p in c.people 
p.country= c

to get a back link. 

But the problem is that the deserializer actually creates the same person in multiple countries as the id is the same by reference. Then I cannot have them have a different country in the model (if i change country for one object I will change it for another as well).

my question is  - can you create an option that objects which are same by id don't created the same by reference (but only by content)?

thanks in advance, 
Ivan

**Comment by alex-davies** [comment]
You need to give `Person` an `Id` property. When you give it an Id it will treat a person as an entity. Without an id it treat it as attribute data.

But it seems like you are having an issue where we only deserialise one object, even if there are multiple references to it . This is by design and the and the intention of jsonapi. If an object has the same id and type, it is the same object.

Your object model at the moment does not support a person being in multiple countries. Your model currently states a person can only have a single country. You could easily fix your model by allowing a `Person` to have a list of countries instead of just one.
