### ISSUE TITLE
Class with JObject as a property is being serialized as a relationship

### ISSUE THREAD

**Issue by jazpearson** [codecutout/JsonApiSerializer#61]
I have the following classes:

```
    public class MyClass
    {
        public string Id { get; set; }

        public NestedClass MyObject { get; set; }
    }

    public class NestedClass
    {
        public JObject Data { get; set; } 
    }
```

and if i do the following:

```
            var doc = new DocumentRoot<MyClass>()
                    {
                        Data = new MyClass()
                               {
                                   MyObject = new NestedClass()
                                              {
                     
                                              }
                               }
                    };

            
            var json = JsonConvert.SerializeObject(doc, new JsonApiSerializerSettings());
```

this will produce:

```
{
  "data": {
    "type": "myclass",
    "relationships": {
      "myObject": {
        
      }
    }
  }
}
```

where i'm needing `myObject` to be an attribute, not a relationship. Is there something i can do to mitigate this? I assume it's because a `JObject` has a `Type` property....

**Comment by alex-davies** [comment]
It will be because your NestedClass has a property called `data` so it is mistaking it for a relationship object (similar to https://github.com/codecutout/JsonApiSerializer/blob/master/src/JsonApiSerializer/JsonApi/Relationship.cs)

 The simple workaround is to avoid naming things `data` unless you want to specify a relationship (with meta and links), just change the the type of the `MyObject` property to be `JObject` directly. 

The json:api spec makes heavy use of  `data` fields names in relationships, and although the spec allows a `data` field on the attributes, id avoid doing it as it can add a lot of confusion to your contract.

**Comment by jazpearson** [comment]
ah ok.

I found that i can rename my `Data` property as `MyData` for example, and then use the `JsonProperty` attribute to name it `data`. 
The case i'm showing here is very simplified, but the api i am writing for requires using `data` like i've shown so there's no getting round it for me in this instance.

thanks for the help.
