### ISSUE TITLE
Does not handle null data field

### ISSUE THREAD

**Issue by OKTAYKIR** [codecutout/JsonApiSerializer#7]
I experience an exception when deserialize an object.

Example:
{"data": null}

Exception:
JsonApiSerializer.Exceptions.JsonApiFormatException: 'Unable to find closing element element'.

**Comment by alex-davies** [comment]
This is indeed a bug, I have just created a fix in 0.9.14.

However there may be some unobvious behaviour here; When deserializing as a list the item will return as an empty list rather than null. Although i'm not entirely keen on this behaviour, there is precedent in other parts of the library where this is how it handles null lists so changing it would be a breaking change.
